on:
  push:
    branches: [ "main" ]
jobs:
  ansible_demo:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run Ansible Playbook
        run: ansible-playbook create_rg.yml
