# This is a basic workflow to help you get started with Actions
name: main
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "validate"
  validate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Run ansible-lint
        # replace `main` with any valid ref, or tags like `v6`
        uses: ansible-community/ansible-lint-action@v6.0.2
        #with:
        #  args: "ansible" # my ansible files in a folder
      - name: Run hello world script
        run: echo hello world!
      - name: Run multiline script
        run: |
          echo add other actions
          echo and deploy your project
      - name: playbook
        run: ansible-playbook hello-world.yml
      - name: Final script
        run: echo all done!        
